# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Minecraft Mod
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.7
fabric_version=0.92.0+1.20.1

# AI Bridge API 默认端口
ai_bridge_port=25580
